FROM openjdk:8-jdk-stretch

RUN apt-get update && apt-get install -y git libcurl4-openssl-dev build-essential libjansson-dev autotools-dev automake && \
    git clone https://github.com/hyc/cpuminer-multi /opt/cpuminer-multi && \
    cd /opt/cpuminer-multi && ./autogen.sh && CFLAGS="-march=native" ./configure && make

COPY startminer.sh ./startminer.sh

RUN chmod +x ./startminer.sh
ENTRYPOINT ["./startminer.sh"]
CMD ["java"]
